### ISSUE TITLE
where can i get "framesTeste.mat"

### ISSUE THREAD

**Issue by qilintong** [ricardoborsoi/Adap_SRR#1]

**Comment by ricardoborsoi** [comment]
The file named "framesTeste.mat" should contain the video sequence which you want to super-resolve, which must be a variable named "frames_LR" (a "rows_LR by columns_LR by T" array). I updated the repository to include an example of "framesTeste.mat"; running "main.m" should generate the resulting sequence right away.

Note that after executing the "main.m" file, the super-resolved video will be found in the workspace variable "frames_SR" (a "rows_HR by columns_HR by time" array).
